language: python
python:
  - "3.7.4"
before-install: 
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest -s tests/test_pytest.py
  - python -m unittest tests/test_unittest.py